name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      ## https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: cache-${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-${{ runner.OS }}-build-${{ env.cache-name }}-
            cache-${{ runner.OS }}-build-
            cache-${{ runner.OS }}-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm install
          npm run build:ci